<?php

/**
 * @file
 * tawk_to - integration with https://www.tawk.to chat service
 * Contains main module code.
 */
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\file\Entity\File;
use Drupal\Core\Template\Attribute;
use Drupal\Core\Url;
use Drupal\tawk_to\Controller\TawkToWidgetController;
use Drupal\Core\Render\Markup;

/**
 * Implements hook_help
 * @see hook_help()
 */
function tawk_to_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.tawk_to':
      return t('
        <h2>http://tawk.to for Drupal 8.</h2>
        <p>Tawk.to widget cutomization, using this module you can select widget which will be used on every page on your site</p>
      ');
  }
}

/**
 * Implements hook_page_bottom
 * Hook for adding widget script to every page.
 * @see hook_page_bottom()
 */
function tawk_to_page_bottom(array &$page_bottom) {
  $widget = TawkToWidgetController::tawkToGetWidget();

  if ($widget['page_id'] === '' || $widget['widget_id'] === '') {
    return NULL;
  }
  $is_admin = \Drupal::service('router.admin_context')->isAdminRoute();
  // Disable widget for admin pages.
  if(!$is_admin){
    $page_id = $widget['page_id'];
    $widget_id = $widget['widget_id'];
    $items = array();
    $items['page_id'] = $widget['page_id'];
    $items['widget_id'] = $widget['widget_id'];
    $page_bottom['tawk_to_widget'] = array('#theme' => 'tawk_to', '#items' => $items);
  }
}

/**
 * Implements hook_theme().
 */
function tawk_to_theme($existing, $type, $theme, $path) {
  return array(
    'tawk_to' => array(
      'variables' => array(
        'items' => array(),
      )
    ),
    'tawk_to_iframe' => array(
      'variables' => array(
        'items' => array(),
      )
    ),
  );
}
