<?php

/**
 * @file
 * Contains main module code.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 *
 * @see hook_help()
 */
function tawk_to_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.tawk_to':
      return t('
        <h2>http://tawk.to for Drupal 8.</h2>
        <p>Tawk.to widget cutomization, using this module you can select widget which will be used on every page on your site</p>
      ');
  }
}

/**
 * Implements hook_page_bottom().
 *
 * Hook for adding widget script to every page.
 *
 * @see hook_page_bottom()
 */
function tawk_to_page_bottom(array &$page_bottom) {
  $page_id = \Drupal::config('tawk_to.settings')->get('tawk_to_widget_page_id');
  $widget_id = \Drupal::config('tawk_to.settings')->get('tawk_to_widget_widget_id');
  if ($page_id === '' || $widget_id === '') {
    return NULL;
  }
  $is_admin_page = \Drupal::service('router.admin_context')->isAdminRoute();
  $check_access = \Drupal::currentUser()->hasPermission('access tawk_to widget');
  // Disable widget for admin pages.
  if (!$is_admin_page && $check_access) {
    $items = [];
    $items['page_id'] = $page_id;
    $items['widget_id'] = $widget_id;
    $page_bottom['tawk_to_widget'] = ['#theme' => 'tawk_to', '#items' => $items];
  }
}

/**
 * Implements hook_theme().
 */
function tawk_to_theme($existing, $type, $theme, $path) {
  return [
    'tawk_to' => [
      'variables' => [
        'items' => [],
      ],
    ],
    'tawk_to_iframe' => [
      'variables' => [
        'items' => [],
      ],
    ],
  ];
}
